name: ${project.name}
version: ${version.build}
description: ${project.description}
authors: [Crypnotic]
main: ${project.groupId}.EmpiresPlugin
commands:
    empire:
        description: The central command to access functions relating to EmpiresPlugin
        usage: /empire (command)
        aliases: [em, empires]